("undefined"==typeof Crypto||!Crypto.util)&&function(){var a=window.Crypto={},b=a.util={rotl:function(a,b){return a<<b|a>>>32-b},rotr:function(a,b){return a<<32-b|a>>>b},endian:function(a){if(a.constructor==Number)return b.rotl(a,8)&16711935|b.rotl(a,24)&4278255360;for(var c=0;c<a.length;c++)a[c]=b.endian(a[c]);return a},randomBytes:function(a){for(var b=[];0<a;a--)b.push(Math.floor(256*Math.random()));return b},bytesToWords:function(a){for(var b=[],c=0,g=0;c<a.length;c++,g+=8)b[g>>>5]|=a[c]<<24-
g%32;return b},wordsToBytes:function(a){for(var b=[],c=0;c<32*a.length;c+=8)b.push(a[c>>>5]>>>24-c%32&255);return b},bytesToHex:function(a){for(var b=[],c=0;c<a.length;c++)b.push((a[c]>>>4).toString(16)),b.push((a[c]&15).toString(16));return b.join("")},hexToBytes:function(a){for(var b=[],c=0;c<a.length;c+=2)b.push(parseInt(a.substr(c,2),16));return b},bytesToBase64:function(a){if("function"==typeof btoa)return btoa(c.bytesToString(a));for(var b=[],f=0;f<a.length;f+=3)for(var g=a[f]<<16|a[f+1]<<8|
a[f+2],i=0;4>i;i++)8*f+6*i<=8*a.length?b.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(g>>>6*(3-i)&63)):b.push("=");return b.join("")},base64ToBytes:function(a){if("function"==typeof atob)return c.stringToBytes(atob(a));for(var a=a.replace(/[^A-Z0-9+\/]/ig,""),b=[],f=0,g=0;f<a.length;g=++f%4)0!=g&&b.push(("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a.charAt(f-1))&Math.pow(2,-2*g+8)-1)<<2*g|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a.charAt(f))>>>
6-2*g);return b}};a.mode={};a=a.charenc={};a.UTF8={stringToBytes:function(a){return c.stringToBytes(unescape(encodeURIComponent(a)))},bytesToString:function(a){return decodeURIComponent(escape(c.bytesToString(a)))}};var c=a.Binary={stringToBytes:function(a){for(var b=[],c=0;c<a.length;c++)b.push(a.charCodeAt(c)&255);return b},bytesToString:function(a){for(var b=[],c=0;c<a.length;c++)b.push(String.fromCharCode(a[c]));return b.join("")}}}();
(function(){var a=Crypto,b=a.util,c=a.charenc,d=c.UTF8,e=c.Binary,f=a.SHA1=function(a,c){var d=b.wordsToBytes(f._sha1(a));return c&&c.asBytes?d:c&&c.asString?e.bytesToString(d):b.bytesToHex(d)};f._sha1=function(a){a.constructor==String&&(a=d.stringToBytes(a));var c=b.bytesToWords(a),e=8*a.length,a=[],f=1732584193,j=-271733879,l=-1732584194,m=271733878,q=-1009589776;c[e>>5]|=128<<24-e%32;c[(e+64>>>9<<4)+15]=e;for(e=0;e<c.length;e+=16){for(var h=f,o=j,r=l,p=m,s=q,t=0;80>t;t++){if(16>t)a[t]=c[e+t];else{var u=
a[t-3]^a[t-8]^a[t-14]^a[t-16];a[t]=u<<1|u>>>31}u=(f<<5|f>>>27)+q+(a[t]>>>0)+(20>t?(j&l|~j&m)+1518500249:40>t?(j^l^m)+1859775393:60>t?(j&l|j&m|l&m)-1894007588:(j^l^m)-899497514);q=m;m=l;l=j<<30|j>>>2;j=f;f=u}f+=h;j+=o;l+=r;m+=p;q+=s}return[f,j,l,m,q]};f._blocksize=16;f._digestsize=20})();
(function(){var a=Crypto,b=a.util,c=a.charenc,d=c.UTF8,e=c.Binary;a.HMAC=function(a,c,i,k){c.constructor==String&&(c=d.stringToBytes(c));i.constructor==String&&(i=d.stringToBytes(i));i.length>4*a._blocksize&&(i=a(i,{asBytes:!0}));for(var n=i.slice(0),i=i.slice(0),j=0;j<4*a._blocksize;j++)n[j]^=92,i[j]^=54;a=a(n.concat(a(i.concat(c),{asBytes:!0})),{asBytes:!0});return k&&k.asBytes?a:k&&k.asString?e.bytesToString(a):b.bytesToHex(a)}})();
(function(){var a=Crypto,b=a.util,c=a.charenc,d=c.UTF8,e=c.Binary;a.PBKDF2=function(c,g,i,k){c.constructor==String&&(c=d.stringToBytes(c));g.constructor==String&&(g=d.stringToBytes(g));for(var n=k&&k.hasher||a.SHA1,j=k&&k.iterations||1,l=[],m=1;l.length<i;){var q;q=g.concat(b.wordsToBytes([m]));for(var h=q=a.HMAC(n,q,c,{asBytes:!0}),o=1;o<j;o++)for(var h=a.HMAC(n,h,c,{asBytes:!0}),r=0;r<q.length;r++)q[r]^=h[r];l=l.concat(q);m++}l.length=i;return k&&k.asBytes?l:k&&k.asString?e.bytesToString(l):b.bytesToHex(l)}})();
(function(){function a(a,c,d){for(var e=4*a._blocksize,d=d.slice(0),f=0;f<c.length;f++)0==f%e&&a._encryptblock(d,0),c[f]^=d[f%e]}Crypto.mode.OFB={encrypt:a,decrypt:a}})();
(function(){function a(a,b){for(var c=0,d=0;8>d;d++){b&1&&(c^=a);var e=a&128,a=a<<1&255;e&&(a^=27);b>>>=1}return c}for(var b=Crypto,c=b.util,d=b.charenc.UTF8,e=[99,124,119,123,242,107,111,197,48,1,103,43,254,215,171,118,202,130,201,125,250,89,71,240,173,212,162,175,156,164,114,192,183,253,147,38,54,63,247,204,52,165,229,241,113,216,49,21,4,199,35,195,24,150,5,154,7,18,128,226,235,39,178,117,9,131,44,26,27,110,90,160,82,59,214,179,41,227,47,132,83,209,0,237,32,252,177,91,106,203,190,57,74,76,88,207,
208,239,170,251,67,77,51,133,69,249,2,127,80,60,159,168,81,163,64,143,146,157,56,245,188,182,218,33,16,255,243,210,205,12,19,236,95,151,68,23,196,167,126,61,100,93,25,115,96,129,79,220,34,42,144,136,70,238,184,20,222,94,11,219,224,50,58,10,73,6,36,92,194,211,172,98,145,149,228,121,231,200,55,109,141,213,78,169,108,86,244,234,101,122,174,8,186,120,37,46,28,166,180,198,232,221,116,31,75,189,139,138,112,62,181,102,72,3,246,14,97,53,87,185,134,193,29,158,225,248,152,17,105,217,142,148,155,30,135,233,
206,85,40,223,140,161,137,13,191,230,66,104,65,153,45,15,176,84,187,22],f=[],g=0;256>g;g++)f[e[g]]=g;for(var i=[],k=[],n=[],j=[],l=[],m=[],g=0;256>g;g++)i[g]=a(g,2),k[g]=a(g,3),n[g]=a(g,9),j[g]=a(g,11),l[g]=a(g,13),m[g]=a(g,14);var q=[0,1,2,4,8,16,32,64,128,27,54],h=[[],[],[],[]],o,r,p,s=b.AES={encrypt:function(a,e,f){var f=f||{},a=d.stringToBytes(a),g=f.iv||c.randomBytes(4*s._blocksize),e=e.constructor==String?b.PBKDF2(e,g,32,{asBytes:!0}):e,i=f.mode||b.mode.OFB;s._init(e);i.encrypt(s,a,g);return c.bytesToBase64(f.iv?
a:g.concat(a))},decrypt:function(a,e,f){var f=f||{},a=c.base64ToBytes(a),g=f.iv||a.splice(0,4*s._blocksize),e=e.constructor==String?b.PBKDF2(e,g,32,{asBytes:!0}):e,f=f.mode||b.mode.OFB;s._init(e);f.decrypt(s,a,g);return d.bytesToString(a)},_blocksize:4,_encryptblock:function(a,b){for(var c=0;c<s._blocksize;c++)for(var d=0;4>d;d++)h[c][d]=a[b+4*d+c];for(c=0;4>c;c++)for(d=0;4>d;d++)h[c][d]^=p[d][c];for(var f=1;f<r;f++){for(c=0;4>c;c++)for(d=0;4>d;d++)h[c][d]=e[h[c][d]];h[1].push(h[1].shift());h[2].push(h[2].shift());
h[2].push(h[2].shift());h[3].unshift(h[3].pop());for(d=0;4>d;d++){var c=h[0][d],g=h[1][d],j=h[2][d],l=h[3][d];h[0][d]=i[c]^k[g]^j^l;h[1][d]=c^i[g]^k[j]^l;h[2][d]=c^g^i[j]^k[l];h[3][d]=k[c]^g^j^i[l]}for(c=0;4>c;c++)for(d=0;4>d;d++)h[c][d]^=p[4*f+d][c]}for(c=0;4>c;c++)for(d=0;4>d;d++)h[c][d]=e[h[c][d]];h[1].push(h[1].shift());h[2].push(h[2].shift());h[2].push(h[2].shift());h[3].unshift(h[3].pop());for(c=0;4>c;c++)for(d=0;4>d;d++)h[c][d]^=p[4*r+d][c];for(c=0;c<s._blocksize;c++)for(d=0;4>d;d++)a[b+4*
d+c]=h[c][d]},_decryptblock:function(a,c){for(var b=0;b<s._blocksize;b++)for(var d=0;4>d;d++)h[b][d]=a[c+4*d+b];for(b=0;4>b;b++)for(d=0;4>d;d++)h[b][d]^=p[4*r+d][b];for(var e=1;e<r;e++){h[1].unshift(h[1].pop());h[2].push(h[2].shift());h[2].push(h[2].shift());h[3].push(h[3].shift());for(b=0;4>b;b++)for(d=0;4>d;d++)h[b][d]=f[h[b][d]];for(b=0;4>b;b++)for(d=0;4>d;d++)h[b][d]^=p[4*(r-e)+d][b];for(d=0;4>d;d++){var b=h[0][d],g=h[1][d],i=h[2][d],k=h[3][d];h[0][d]=m[b]^j[g]^l[i]^n[k];h[1][d]=n[b]^m[g]^j[i]^
l[k];h[2][d]=l[b]^n[g]^m[i]^j[k];h[3][d]=j[b]^l[g]^n[i]^m[k]}}h[1].unshift(h[1].pop());h[2].push(h[2].shift());h[2].push(h[2].shift());h[3].push(h[3].shift());for(b=0;4>b;b++)for(d=0;4>d;d++)h[b][d]=f[h[b][d]];for(b=0;4>b;b++)for(d=0;4>d;d++)h[b][d]^=p[d][b];for(b=0;b<s._blocksize;b++)for(d=0;4>d;d++)a[c+4*d+b]=h[b][d]},_init:function(a){o=a.length/4;r=o+6;s._keyexpansion(a)},_keyexpansion:function(a){p=[];for(var b=0;b<o;b++)p[b]=[a[4*b],a[4*b+1],a[4*b+2],a[4*b+3]];for(b=o;b<s._blocksize*(r+1);b++)a=
[p[b-1][0],p[b-1][1],p[b-1][2],p[b-1][3]],0==b%o?(a.push(a.shift()),a[0]=e[a[0]],a[1]=e[a[1]],a[2]=e[a[2]],a[3]=e[a[3]],a[0]^=q[b/o]):6<o&&4==b%o&&(a[0]=e[a[0]],a[1]=e[a[1]],a[2]=e[a[2]],a[3]=e[a[3]]),p[b]=[p[b-o][0]^a[0],p[b-o][1]^a[1],p[b-o][2]^a[2],p[b-o][3]^a[3]]}}})();var isNodejs=!1;
if("undefined"!=typeof require)crypto=require("crypto"),jsdom=require("jsdom"),XMLHttpRequest=require("./lib/XMLHttpRequest.js").XMLHttpRequest,isNodejs=!0;else{if(!Array.prototype.forEach)Array.prototype.forEach=function(a,b){var c=this.length;if("function"!=typeof a)throw new TypeError;for(var d=0;d<c;d++)d in this&&a.call(b,this[d],d,this)};if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};if(!Object.keys)Object.keys=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&
b.push(c);return b}}function dumpObject(a,b){"undefined"==typeof b&&(b=1);if(0>b)return a;var c="[",d;for(d in a)if(a.hasOwnProperty(d)){var e=a[d];"object"===typeof e&&null!=e&&(e=dumpObject(e,b-1));c+=d+"="+e+", "}1<c.length&&(c=c.substr(0,c.length-2));return c+"]"}function AtmosRange(a,b){this.offset=a;this.size=b}AtmosRange.prototype.toString=function(){return"bytes="+this.offset+"-"+(this.offset+this.size-1)};function AtmosResult(a,b){this.success=a;this.state=b}
function Acl(a,b){this.userEntries=a;this.groupEntries=b}function AclEntry(a,b){this.key=a;this.value=b}AclEntry.ACL_PERMISSIONS={READ:"READ",WRITE:"WRITE",FULL_CONTROL:"FULL_CONTROL",NONE:"NONE"};AclEntry.GROUPS={OTHER:"other"};function ListOptions(a,b,c,d,e){this.limit=a;this.token=b;this.includeMeta=c;this.userMetaTags=d;this.systemMetaTags=e}function ObjectResult(a,b,c,d){this.objectId=this.id=a;this.userMeta=b;this.listableUserMeta=c;this.systemMeta=d}
function DirectoryItem(a,b,c,d,e,f,g){this.path=this.id=a;this.name=b;this.type=c;this.objectId=d;this.userMeta=e;this.listableUserMeta=f;this.systemMeta=g}function ObjectInfo(a,b,c,d,e,f,g){this.objectId=a;this.selection=b;this.replicas=c;this.expirationEnabled=d;this.expirationEndsAt=e;this.retentionEnabled=f;this.retentionEndsAt=g}function ObjectReplica(a,b,c,d,e){this.id=a;this.location=b;this.replicaType=c;this.current=d;this.storageType=e}
function AjaxRequest(a){this.uri=a.uri;this.method=a.method;this.headers=a.headers;this.data=a.data;this.mimeType=a.mimeType;this.range=a.range;this.progress=a.progress;this.processResult=a.processResult;this.complete=a.complete;this.form=a.form;this.state=a.state}function AtmosServiceInfo(a,b,c,d,e,f){this.version=a;this.object=b;this.namespace=c;this.utf8=d;this.browsercompat=e;this.keyvalue=f}var AtmosRest=function(a){this.atmosConfig=a;this.info("AtmosRest loaded")};AtmosRest.iframeCount=0;
AtmosRest.prototype.context="/rest";
AtmosRest.prototype.getServiceInformation=function(a,b){var c=this;this._ajax(new AjaxRequest({method:"GET",uri:this.context+"/service",headers:{},state:a,processResult:function(a,b){if(a.success){var f="n/a",g=c._getXmlDoc(b).getElementsByTagName("Version");g.length&&(f=c._getText(c._getChildByTagName(g[0],"Atmos")));a.value=new AtmosServiceInfo(f,!1,!1,!1,!1,!1);if(f=b.getResponseHeader("x-emc-features")){f=f.split(", ");for(g=0;g<f.length;g++)f[g]=f[g].replace(/-/g,""),a.value[f[g]]=!0}else a.value.object=
!0,a.value.namespace=!0,a.value.utf8="true"==b.getResponseHeader("x-emc-support-utf8")}},complete:b}))};AtmosRest.prototype.createObject=function(a,b,c,d,e,f,g,i,k){var n={},j=this;this._addAclHeaders(a,n);this._addMetadataHeaders(b,n,!1);this._addMetadataHeaders(c,n,!0);this._ajax(new AjaxRequest({uri:this.context+"/objects",method:"POST",headers:n,data:e,mimeType:f,progress:k,processResult:function(a,b){a.success&&j._processCreateObjectResult(a,b)},complete:i,form:d,state:g}))};
AtmosRest.prototype.createObjectOnPath=function(a,b,c,d,e,f,g,i,k,n){if(!AtmosRest.objectPathMatch.test(a))throw"The path '"+a+"' is not valid";var j={},l=this;this._addAclHeaders(b,j);this._addMetadataHeaders(c,j,!1);this._addMetadataHeaders(d,j,!0);this._ajax(new AjaxRequest({uri:this._getPath(a),method:"POST",headers:j,data:f,mimeType:g,progress:n,processResult:function(a,b){a.success&&l._processCreateObjectResult(a,b)},complete:k,form:e,state:i}))};
AtmosRest.prototype.readObject=function(a,b,c,d){this._ajax(new AjaxRequest({uri:this._getPath(a),method:"GET",headers:{},range:b,processResult:function(a,b){if(a.success)a.data=b.responseText},complete:d,state:c}))};
AtmosRest.prototype.updateObject=function(a,b,c,d,e,f,g,i,k,n,j){var l={};this._addAclHeaders(b,l);this._addMetadataHeaders(c,l,!1);this._addMetadataHeaders(d,l,!0);this._ajax(new AjaxRequest({uri:this._getPath(a),method:"PUT",headers:l,data:f,mimeType:i,range:g,progress:j,complete:n,form:e,state:k}))};AtmosRest.prototype.deleteObject=function(a,b,c){this._ajax(new AjaxRequest({uri:this._getPath(a),method:"DELETE",headers:{},complete:c,state:b}))};
AtmosRest.prototype.listVersions=function(a,b,c){var d=this;this._ajax(new AjaxRequest({uri:this._getPath(a)+"?versions",method:"GET",headers:{},processResult:function(a,b){if(a.success)a.value=d._parseObjectVersions(b)},complete:c,state:b}))};AtmosRest.prototype.versionObject=function(a,b,c){var d=this;this._ajax(new AjaxRequest({uri:this._getPath(a)+"?versions",method:"POST",headers:{},processResult:function(a,b){a.success&&d._processCreateObjectResult(a,b)},complete:c,state:b}))};
AtmosRest.prototype.restoreVersion=function(a,b,c,d){var e={};e["x-emc-version-oid"]=b;this._ajax(new AjaxRequest({uri:this._getPath(a)+"?versions",method:"PUT",headers:e,complete:d,state:c}))};AtmosRest.prototype.deleteVersion=function(a,b,c){this._ajax(new AjaxRequest({uri:this._getPath(a)+"?versions",method:"DELETE",headers:{},complete:c,state:b}))};
AtmosRest.prototype.rename=function(a,b,c,d,e){if(!AtmosRest.objectPathMatch.test(b))throw"The path '"+b+"' is not valid";var f={};f["x-emc-path"]=this.atmosConfig.utf8Support?encodeURIComponent(b.substr(1)):b.substr(1);c&&(f["x-emc-force"]="true");this._ajax(new AjaxRequest({uri:this._getPath(a)+"?rename",method:"POST",headers:f,complete:e,state:d}))};AtmosRest.prototype.createAttachmentDisposition=function(a){return a?"attachment; filename*="+encodeURIComponent("UTF-8''"+a):"attachment"};
AtmosRest.prototype.getShareableUrl=function(a,b,c){if(!b.getTime)throw"expirationDate must be a Date object";var a=this._getPath(a),d=Math.floor(b.getTime()/1E3),b="GET\n"+a.toLowerCase()+"\n"+this.atmosConfig.uid+"\n"+d;c&&(b+="\n"+c);this.info("hash string:\n"+b);var e=this._doSignature(b,this.atmosConfig.secret),b="uid="+encodeURIComponent(this.atmosConfig.uid),b=b+("&expires="+d)+("&signature="+encodeURIComponent(e));c&&(b+="&disposition="+encodeURIComponent(c));"undefined"!=typeof window?(c=
window.location.protocol,d=window.location.host):(c=this.atmosConfig.protocol,d=this.atmosConfig.host);a=c+"//"+d+this._encodeURI(a)+"?"+b;this.info("Shareable URL: "+a);return a};
AtmosRest.prototype.getAcl=function(a,b,c){var d=this;this._ajax(new AjaxRequest({uri:this._getPath(a)+"?acl",method:"GET",headers:{},processResult:function(a,b){if(a.success){var c=d._parseAclEntries(b.getResponseHeader("x-emc-useracl")),i=d._parseAclEntries(b.getResponseHeader("x-emc-groupacl"));a.value=new Acl(c,i)}},complete:c,state:b}))};
AtmosRest.prototype.setAcl=function(a,b,c,d){var e={};this._addAclHeaders(b,e);this._ajax(new AjaxRequest({uri:this._getPath(a)+"?acl",method:"POST",headers:e,complete:d,state:c}))};
AtmosRest.prototype.listUserMetadataTags=function(a,b,c){var d=this;this._ajax(new AjaxRequest({uri:this._getPath(a)+"?metadata/tags",method:"GET",headers:{},processResult:function(a,b){if(a.success){var c="true"==b.getResponseHeader("x-emc-utf8");a.value={};var i=b.getResponseHeader("x-emc-tags");if(i)a.value.tags=d._listToArray(i,c);if(i=b.getResponseHeader("x-emc-listable-tags"))a.value.listableTags=d._listToArray(i,c)}},complete:c,state:b}))};
AtmosRest.prototype.getUserMetadata=function(a,b,c,d){var e={},f=this;b&&this._addTagHeader(b,e);this._ajax(new AjaxRequest({uri:this._getPath(a)+"?metadata/user",method:"GET",headers:e,processResult:function(a,b){if(a.success){var c="true"==b.getResponseHeader("x-emc-utf8");a.value={};a.value.meta=f._parseMetadata(b.getResponseHeader("x-emc-meta"),c);a.value.listableMeta=f._parseMetadata(b.getResponseHeader("x-emc-listable-meta"),c)}},complete:d,state:c}))};
AtmosRest.prototype.getSystemMetadata=function(a,b,c,d){var e={},f=this;b&&this._addTagHeader(b,e);this._ajax(new AjaxRequest({uri:this._getPath(a)+"?metadata/system",method:"GET",headers:e,processResult:function(a,b){if(a.success){var c="true"==b.getResponseHeader("x-emc-utf8");a.value={};a.value.systemMeta=f._parseMetadata(b.getResponseHeader("x-emc-meta"),c);a.value.systemMeta.mimeType=b.getResponseHeader("Content-Type")}},complete:d,state:c}))};
AtmosRest.prototype.getAllMetadata=function(a,b,c){var d=this;this._ajax(new AjaxRequest({uri:this._getPath(a),method:"HEAD",headers:{},processResult:function(a,b){if(a.success){var c="true"==b.getResponseHeader("x-emc-utf8");a.value={};a.value.meta=d._parseMetadata(b.getResponseHeader("x-emc-meta"),c);a.value.listableMeta=d._parseMetadata(b.getResponseHeader("x-emc-listable-meta"),c);var c=d._parseAclEntries(b.getResponseHeader("x-emc-useracl")),i=d._parseAclEntries(b.getResponseHeader("x-emc-groupacl"));
a.value.acl=new Acl(c,i)}},complete:c,state:b}))};AtmosRest.prototype.getObjectInfo=function(a,b,c){var d=this;this._ajax(new AjaxRequest({uri:this._getPath(a)+"?info",method:"GET",headers:{},processResult:function(a,b){a.success&&d._processObjectInfoResult(a,b)},complete:c,state:b}))};
AtmosRest.prototype.setUserMetadata=function(a,b,c,d,e){var f={};this._addMetadataHeaders(b,f,!1);this._addMetadataHeaders(c,f,!0);this._ajax(new AjaxRequest({uri:this._getPath(a)+"?metadata/user",method:"POST",headers:f,complete:e,state:d}))};AtmosRest.prototype.deleteUserMetadata=function(a,b,c,d){var e={};this._addTagHeader(b,e);this._ajax(new AjaxRequest({uri:this._getPath(a)+"?metadata/user",method:"DELETE",headers:e,complete:d,state:c}))};
AtmosRest.prototype.getListableTags=function(a,b,c){var d={},e=this;a&&this._addTagHeader([a],d);this._ajax(new AjaxRequest({uri:this.context+"/objects?listabletags",method:"GET",headers:d,processResult:function(a,b){if(a.success){var c="true"==b.getResponseHeader("x-emc-utf8"),d=b.getResponseHeader("x-emc-listable-tags");if(d)a.value=e._listToArray(d,c)}},complete:c,state:b}))};
AtmosRest.prototype.listObjects=function(a,b,c,d){if(!a)throw"Tag cannot be null";var e={},f=this;this._addTagHeader([a],e);this._addListOptionHeaders(e,b);this._ajax(new AjaxRequest({uri:this.context+"/objects",method:"GET",headers:e,processResult:function(a,b){a.success&&f._processListObjectsResult(a,b)},complete:d,state:c}))};
AtmosRest.prototype.listDirectory=function(a,b,c,d){if(!a)throw"Directory cannot be null";if("/"!==a.charAt(a.length-1))throw"Directory must end with a slash";var e={},f=this;this._addListOptionHeaders(e,b);this._ajax(new AjaxRequest({uri:this.context+"/namespace"+a,method:"GET",headers:e,processResult:function(b,c){b.success&&f._processListDirectoryResult(a,b,c)},complete:d,state:c}))};AtmosRest.locationMatch=/^\/rest\/objects\/(.*)/;AtmosRest.objectPathMatch=/^\//;
AtmosRest.prototype._getPath=function(a){return AtmosRest.objectPathMatch.test(a)?this.context+"/namespace"+a:this.context+"/objects/"+a};AtmosRest.prototype._addAclHeaders=function(a,b){null!=a&&(b["x-emc-useracl"]=this._mapEntriesToString(a.userEntries),b["x-emc-groupacl"]=this._mapEntriesToString(a.groupEntries))};AtmosRest.prototype._mapEntriesToString=function(a){if(void 0==a||1>a.length)return null;for(var b=[],c=0;c<a.length;c++)b.push(a[c].key+"="+a[c].value);return b.join(",")};
AtmosRest.prototype._addTagHeader=function(a,b){for(var c="",d=0;d<a.length;d++)0<d&&(c+=","),c+=this.atmosConfig.utf8Support?encodeURIComponent(a[d]):a[d];b["x-emc-tags"]=c};AtmosRest.prototype._addMetadataHeaders=function(a,b,c){null==a||0==Object.keys(a).length||(c?b["x-emc-listable-meta"]=this._metaToHeaderValue(a):b["x-emc-meta"]=this._metaToHeaderValue(a))};
AtmosRest.prototype._metaToHeaderValue=function(a){for(var b=[],c=Object.keys(a),d=0;d<c.length;d++){var e=this.atmosConfig.utf8Support?encodeURIComponent(c[d]):c[d],f=this.atmosConfig.utf8Support?encodeURIComponent(a[c[d]]):a[c[d]];b.push(e+"="+f)}return b.join(",")};AtmosRest.prototype._listToArray=function(a,b){if(!a)return null;if(0==a.trim().length)return[];for(var c=a.split(","),d=0;d<c.length;d++)c[d]=b?decodeURIComponent(c[d].trim()):c[d].trim();return c};
AtmosRest.prototype._addListOptionHeaders=function(a,b){if(b){b.limit&&(a["x-emc-limit"]=""+b.limit);if(b.token)a["x-emc-token"]=b.token;b.includeMeta&&(a["x-emc-include-meta"]="1",b.userMetaTags&&(a["x-emc-user-tags"]=b.userMetaTags.join(",")),b.systemMetaTags&&(a["x-emc-system-tags"]=b.systemMetaTags.join(",")))}};AtmosRest.prototype._prepBaseHeaders=function(a,b){a["x-emc-date"]=(new Date).toGMTString();b&&(a.Range=b.toString())};
AtmosRest.prototype._prepUploadHeaders=function(a,b){if(""==b||void 0==b)b="text/plain; charset=UTF-8";-1==b.indexOf("charset")&&(b+="; charset=UTF-8");a["Content-Type"]=b};
AtmosRest.prototype._ajax=function(a){a.uri=this._resolveDots(a.uri);a.headers&&(this.atmosConfig.utf8Support&&(a.headers["x-emc-utf8"]="true"),this._prepBaseHeaders(a.headers,a.range),/(POST|PUT)/.test(a.method)&&this._prepUploadHeaders(a.headers,a.mimeType),this._signRequest(a.method,a.headers,a.uri));if(!/^https?:\/\//.test(a.uri)&&(a.uri=this._encodeURI(a.uri),this.atmosConfig.host&&this.atmosConfig.protocol))a.uri=this.atmosConfig.protocol+"//"+this.atmosConfig.host+a.uri;var b=this,c=function(c){var d=
b._createResult(c,400>c.status,a.state);a.processResult&&a.processResult(d,c);a.complete&&a.complete(d)};if(a.form){a.headers["x-http-inject-response-headers"]="true";if("POST"!=a.method)a.headers["x-http-method-override"]=a.method;var d=this._createTargetIframe(function(a){a=b._parseFormResponse(a);c(a)});this._setFormHeaders(a.form,a.headers);a.progress&&a.progress(-1);a.form.action=a.uri;a.form.method="POST";a.form.enctype=a.form.encoding="multipart/form-data";a.form.target=d.name;a.form.submit()}else{var e=
this._getXMLHttpRequest();e.onreadystatechange=function(){4==e.readyState&&c(e)};try{if(a.progress)(e.upload||e).onprogress=function(b){b.lengthComputable&&a.progress(Math.floor(100*((b.position||b.loaded)/(b.totalSize||b.total))))}}catch(f){a.progress(-1)}e.open(a.method,a.uri,!0);this._setHeaders(e,a.headers);a.data?e.send(a.data):e.send()}};AtmosRest.prototype._getXMLHttpRequest=function(){if(isNodejs)return new XMLHttpRequest;if(window.XMLHttpRequest)return new window.XMLHttpRequest;try{return new ActiveXObject("MSXML2.XMLHTTP.3.0")}catch(a){return null}};
AtmosRest.prototype._setFormHeaders=function(a,b){for(var c=Object.keys(b),d=0;d<c.length;d++){var e=a.elements[c[d]];if(!e){try{e=document.createElement('<input type="hidden" name="'+c[d]+'">')}catch(f){e=document.createElement("input"),e.name=c[d]}e.type="hidden";a.insertBefore(e,a.childNodes[0])}e.value=b[c[d]]}};
AtmosRest.prototype._createTargetIframe=function(a){var b="ATMOS_IFRAME_"+ ++AtmosRest.iframeCount,c;try{c=document.createElement('<iframe name="'+b+'"></iframe>')}catch(d){c=document.createElement("iframe"),c.name=b}c.id=b;c.style.display="none";document.body.appendChild(c);b=function(){var b=c.contentDocument||c.contentWindow.document;a.call(c,null!=b.body?b.body.firstChild.innerHTML:b.documentElement.innerHTML);document.body.removeChild(c)};c.attachEvent?c.attachEvent("onload",b):c.onload=b;return c};
AtmosRest.prototype._parseFormResponse=function(a){this.debug("form response (raw):\n"+a);var b={headers:{}},c;try{var d=0,e=function(b){var c=a.indexOf("\n");if(0>c)c=a.length;var e=a.substr(0,c);b&&(a=a.substr(c+1),d+=c+1);return e};c=parseInt(e(!1));if(!isNaN(c)){e(!0);var f=e(!0),g=f.split(" ");b.status=parseInt(g[1]);for(b.statusText=f.substr(g[0].length+g[1].length+2);d<c;){var i=e(!0),k=i.indexOf(": ");b.headers[i.substr(0,k)]=i.substr(k+2)}}}catch(n){this.warn("could not parse headers in form response: "+
n)}b.getResponseHeader=function(a){return this.headers[a]};b.responseText=this._decodeXmlEntities(a);return b};AtmosRest.prototype._decodeXmlEntities=function(a){a=a.replace(/&gt;/g,">");return a=a.replace(/&lt;/g,"<")};AtmosRest.prototype._resolveDots=function(a){if(!a)return a;for(var a=a.split("/"),b=0;b<a.length;b++)".."==a[b]?(a.splice(b-1,2),b-=2):"."==a[b]&&a.splice(b--,1);return a.join("/")};
AtmosRest.prototype._setHeaders=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&a.setRequestHeader(c,b[c])};AtmosRest.prototype._encodeURI=function(a){this.debug("encodeURI: in: "+a);var b=a.indexOf("?"),c="";-1!=b&&(c=a.substring(b),a=a.substring(0,b));for(var a=a.split("/"),d=0;d<a.length;d++)a[d]=encodeURIComponent(a[d]);a=a.join("/");-1!=b&&(a+=encodeURI(c));this.debug("encodeURI: out: "+a);return a};
AtmosRest.prototype._createResult=function(a,b,c){c=new AtmosResult(b,c);c.httpCode=a.status;c.httpMessage=a.statusText;if(!b&&(a=this._getXmlDoc(a).getElementsByTagName("Error"),a.length))c.errorCode=this._getText(this._getChildByTagName(a[0],"Code")),c.errorMessage=this._getText(this._getChildByTagName(a[0],"Message"));return c};AtmosRest.prototype._getXmlDoc=function(a){if(a.responseXML)return a.responseXML;this.debug("response:\n"+a.responseText);return this._createXmlDoc(a.responseText)};
AtmosRest.prototype._createXmlDoc=function(a){if(isNodejs)return jsdom.jsdom(a);if(window.DOMParser)return(new DOMParser).parseFromString(a,"text/xml");if("undefined"!=typeof ActiveXObject){var b=new ActiveXObject("MSXML.DomDocument");b.loadXML(a);return b}};
AtmosRest.prototype._processCreateObjectResult=function(a,b){var c=b.getResponseHeader("location");this.debug("location: "+c);var d=c.match(AtmosRest.locationMatch);null==d?(a.success=!1,a.message="Could not find location in "+c):(a.value=d[1],this.debug("Location: "+a.value))};
AtmosRest.prototype._parseMetadata=function(a,b){if("undefined"==typeof a||null==a||0==a.length)return null;for(var c={},d=a.split(","),e=0;e<d.length;e++){var f=d[e].split("=",2),g=b?decodeURIComponent(f[0].trim()):f[0].trim();c[g]=1==f.length?"":b?decodeURIComponent(f[1]):f[1]}return c};
AtmosRest.prototype._processListObjectsResult=function(a,b){a.token=b.getResponseHeader("x-emc-token");for(var c=[],d=this._getXmlDoc(b).getElementsByTagName("Object"),e=0;e<d.length;e++){var f=null,g=null,i=null,k=d.item(e),n=this._getChildByTagName(k,"ObjectID"),j=this._getChildByTagName(k,"SystemMetadataList"),k=this._getChildByTagName(k,"UserMetadataList");j&&(g={},this._parseResponseMeta(j.childNodes,g,null));k&&(f={},i={},this._parseResponseMeta(k.childNodes,f,i));f=new ObjectResult(this._getText(n),
f,i,g);c.push(f)}a.value=c};
AtmosRest.prototype._processListDirectoryResult=function(a,b,c){b.token=c.getResponseHeader("x-emc-token");for(var d=[],c=this._getXmlDoc(c).getElementsByTagName("DirectoryEntry"),e=0;e<c.length;e++){var f=null,g=null,i=null,k=c.item(e),n=this._getChildByTagName(k,"ObjectID"),j=this._getChildByTagName(k,"Filename"),l=this._getChildByTagName(k,"FileType"),m=this._getChildByTagName(k,"SystemMetadataList"),k=this._getChildByTagName(k,"UserMetadataList");m&&(g={},this._parseResponseMeta(m.childNodes,g,
null));k&&(f={},i={},this._parseResponseMeta(k.childNodes,f,i));f=new DirectoryItem(a+this._getText(j),this._getText(j),this._getText(l),this._getText(n),f,i,g);d.push(f)}b.value=d};
AtmosRest.prototype._processObjectInfoResult=function(a,b){var c=this._getXmlDoc(b),d=null,e=null,f=[],g=!1,i=null,k=!1,n=null,j=c.getElementsByTagName("objectId");j.length&&(d=this._getText(j.item(0)));j=c.getElementsByTagName("selection");j.length&&(e=this._getText(j.item(0)));j=c.getElementsByTagName("replicas");if(j.length)for(var j=this._getChildrenByTagName(j.item(0),"replica"),l=0;l<j.length;l++){var m=j[l],q=this._getText(this._getChildByTagName(m,"id")),h=this._getText(this._getChildByTagName(m,
"location")),o=this._getText(this._getChildByTagName(m,"type")),r=this._getText(this._getChildByTagName(m,"current")),m=this._getText(this._getChildByTagName(m,"storageType"));f.push(new ObjectReplica(q,h,o,r,m))}j=c.getElementsByTagName("expiration");j.length&&(m=j.item(0),g=this._getText(this._getChildByTagName(m,"enabled")),i=this._getText(this._getChildByTagName(m,"endAt")));j=c.getElementsByTagName("retention");j.length&&(m=j.item(0),k=this._getText(this._getChildByTagName(m,"enabled")),n=this._getText(this._getChildByTagName(m,
"endAt")));a.value=new ObjectInfo(d,e,f,g,i,k,n)};AtmosRest.prototype._parseObjectVersions=function(a){for(var b=[],a=this._getXmlDoc(a).getElementsByTagName("Ver"),c=0;c<a.length;c++)b.push(this._getText(this._getChildByTagName(a.item(c),"OID")));return b};AtmosRest.prototype._parseAclEntries=function(a){for(var b=[],a=this._listToArray(a),c=0;c<a.length;c++){var d=a[c].split("=",2),e=d[0],d=d[1],e=e.trim();if("FULL"===d)d=AclEntry.ACL_PERMISSIONS.FULL_CONTROL;b[c]=new AclEntry(e,d)}return b};
AtmosRest.prototype._parseResponseMeta=function(a,b,c){for(var d=0;d<a.length;d++){var e=a.item(d);if(/Metadata/i.test(e.nodeName)){var f=this._getText(this._getChildByTagName(e,"Name")),g=this._getText(this._getChildByTagName(e,"Value"));(e=this._getChildByTagName(e,"Listable"))&&"true"==this._getText(e)?c[f]=g:b[f]=g}}};AtmosRest.prototype._getChildByTagName=function(a,b){var c=this._getChildrenByTagName(a,b);return c.length?c[0]:null};
AtmosRest.prototype._getChildrenByTagName=function(a,b){for(var c=RegExp(b,"i"),d=a.childNodes,e=[],f=0;f<d.length;f++){var g=d.item(f);1==g.nodeType&&c.test(g.nodeName)&&e.push(g)}return e};AtmosRest.prototype._getText=function(a){for(var a=a.childNodes,b="",c=0;c<a.length;c++){var d=a.item(c);3==d.nodeType&&(b+=d.data)}return b};
AtmosRest.prototype._signRequest=function(a,b,c){this.debug(this.atmosConfig.uid);this.debug(this.atmosConfig.secret);var d=b["Content-Type"],e=b.Range,f;f=""==b?new Hash:b;f["x-emc-uid"]=this.atmosConfig.uid;a=this._buildHashString(a,d,e,b.Date,c,f);this.debug("HashString:\n"+a);a=this._doSignature(a,this.atmosConfig.secret);this.debug("Signature: "+a);return f["x-emc-signature"]=a};
AtmosRest.prototype._buildHashString=function(a,b,c,d,e,f){var g={},i="",i=a+"\n",i=b?i+(b+"\n"):i+"\n",i=c?i+(c.toString()+"\n"):i+"\n",i=d?i+(d+"\n"):i+"\n",i=i+(e.toLowerCase().trim()+"\n"),k;for(k in f)f.hasOwnProperty(k)&&(this.debug("headers: prop: "+k+" value: "+f[k]),a=this._normalizeWS(k.toLowerCase().trim()),0!=a.indexOf("x-emc")?this.debug("Skipping "+a):((b=f[k])&&(b=this._normalizeWS(b.trim())),g[a]=b));f=Object.keys(g);this.debug("keys "+f);f.sort().forEach(function(a){i+=a+":"+g[a]+
"\n"});return i.trim()};AtmosRest.prototype._normalizeWS=function(a){if(null==a)return null;a=a.replace(/\n/," ");return a.replace(/\s+/," ")};AtmosRest.prototype._doSignature=function(a,b){this.debug("Secret: "+b);if(isNodejs){var c=new Buffer(b,"base64"),c=crypto.createHmac("sha1",c.toString("binary"));c.update(a);return c.digest("base64")}c=Crypto.HMAC(Crypto.SHA1,a,Crypto.util.base64ToBytes(b),{asBytes:!0});return Crypto.util.bytesToBase64(c)};
AtmosRest.prototype.debug=function(a){"undefined"!==typeof console&&("undefined"!==typeof console.debug?console.debug(a):"undefined"!==typeof console.log&&console.log(a))};AtmosRest.prototype.info=function(a){"undefined"!==typeof console&&"undefined"!==typeof console.info&&console.info(a)};AtmosRest.prototype.warn=function(a){"undefined"!==typeof console&&"undefined"!==typeof console.warn&&console.warn(a)};
AtmosRest.prototype.error=function(a){"undefined"!==typeof console&&"undefined"!==typeof console.error&&console.error(a)};if("undefined"!=typeof exports)exports.AtmosRest=AtmosRest,exports.AtmosRange=AtmosRange,exports.Acl=Acl,exports.AclEntry=AclEntry,exports.AjaxRequest=AjaxRequest,exports.AtmosResult=AtmosResult,exports.AtmosServiceInfo=AtmosServiceInfo,exports.ListOptions=ListOptions,exports.ObjectResult=ObjectResult,exports.DirectoryItem=DirectoryItem,exports.dumpObject=dumpObject;